-- Tradara cloud data model
-- Run this once in Supabase SQL Editor before enabling the cloud-backed app.

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  company_name text not null default '',
  base_location text not null default '',
  company_description text not null default '',
  preferred_trades text[] not null default '{}',
  preferred_project_types text[] not null default '{}',
  max_distance_km numeric not null default 50,
  min_job_value numeric not null default 5000,
  max_job_value numeric not null default 250000,
  target_month date,
  revenue_target numeric not null default 50000,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pipeline (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  development text not null,
  trade text not null,
  status text not null default 'Saved' check (status in ('Saved','Contacted','Quoted','Won','Lost','Not relevant')),
  notes text not null default '',
  est_value numeric not null default 0,
  first_saved date not null default current_date,
  last_updated date not null default current_date,
  unique(user_id, development, trade)
);

alter table public.profiles enable row level security;
alter table public.pipeline enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select using (auth.uid() = user_id);
drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles for insert with check (auth.uid() = user_id);
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "profiles_delete_own" on public.profiles;
create policy "profiles_delete_own" on public.profiles for delete using (auth.uid() = user_id);

drop policy if exists "pipeline_select_own" on public.pipeline;
create policy "pipeline_select_own" on public.pipeline for select using (auth.uid() = user_id);
drop policy if exists "pipeline_insert_own" on public.pipeline;
create policy "pipeline_insert_own" on public.pipeline for insert with check (auth.uid() = user_id);
drop policy if exists "pipeline_update_own" on public.pipeline;
create policy "pipeline_update_own" on public.pipeline for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "pipeline_delete_own" on public.pipeline;
create policy "pipeline_delete_own" on public.pipeline for delete using (auth.uid() = user_id);

create index if not exists pipeline_user_status_idx on public.pipeline(user_id,status);
create index if not exists pipeline_user_trade_idx on public.pipeline(user_id,trade);
